### ISSUE TITLE
get rid of dist

### ISSUE THREAD

**Issue by casperdcl** [iterative/setup-cml#67]
do we really need `dist/` at all? How much speedup does it really bring? Can we just run from source?[^1]

related: #54

[^1]: https://github.com/iterative/setup-cml/pull/62#issuecomment-1109558338

**Comment by dacbd** [comment]
What do you mean by run from source? My understanding is the GitHub node actions basically grab that file and run it ie No npm install or other such things are run, and that's why [they recommend doing it that way](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github) vs checking in node_modules.

**Comment by casperdcl** [comment]
I mean run from `src/` not `dist/`

**Comment by dacbd** [comment]
Without committing node_modules to the repo it wouldn't work/?

**Comment by casperdcl** [comment]
Ah I see https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github - interestingly we're using https://github.com/iterative/setup-cml/blob/4d9a9f255ac51c1cca4d19e58571d637b83886ba/package.json#L57 instead of the recommended `@vercel/ncc`
